=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::CoursesType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CoursesType' do
  before do
    # run before each test
    obj = build(:one_roster_course)
    @instance = OneRosterClient::CoursesType.build_from_hash({:courses => [obj.to_hash]})
  end

  after do
    # run after each test
  end

  describe 'test an instance of CoursesType' do
    it 'should create an instance of CoursesType' do
      expect(@instance).to be_instance_of(OneRosterClient::CoursesType)
    end
  end
  describe 'test attribute "courses"' do
    it 'should work' do
      expect(@instance.courses).to be_a(Array)
    end
    it 'contains courses' do
      @instance.courses.each do |item|
        expect(item).to be_a(OneRosterClient::CourseType)
      end
    end
  end

end
