=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::CourseType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CourseType' do
  before do
    # run before each test
    obj = build(:one_roster_course)
    @instance = OneRosterClient::CourseType.build_from_hash(obj.to_hash)
  end

  after do
    # run after each test
  end

  describe 'test an instance of CourseType' do
    it 'should create an instance of CourseType' do
      expect(@instance).to be_instance_of(OneRosterClient::CourseType)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      expect(@instance.title).to be_a(String)
    end
  end

  describe 'test attribute "school_year"' do
    it 'should work' do
      expect(@instance.school_year).to be_a(OneRosterClient::GUIDRefType)
    end
  end

  describe 'test attribute "course_code"' do
    it 'should work' do
      expect(@instance.course_code).to be_a(String)
    end
  end

  describe 'test attribute "grades"' do
    it 'should work' do
      expect(@instance.grades).to be_a(Array)
    end
  end

  describe 'test attribute "subjects"' do
    it 'should work' do
      expect(@instance.subjects).to be_a(Array)
    end
  end

  describe 'test attribute "org"' do
    it 'should work' do
      expect(@instance.org).to be_a(OneRosterClient::GUIDRefType)
    end
  end

  describe 'test attribute "subject_codes"' do
    it 'should work' do
      expect(@instance.subject_codes).to be_a(Array)
    end
  end

  describe 'test attribute "resources"' do
    it 'should work' do
      expect(@instance.resources).to be_a(Array)
    end
  end

  describe 'test attribute "sourced_id"' do
    it 'should work' do
      expect(@instance.sourced_id).to be_a(String)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(@instance.status).to be_a(String)
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["active", "tobedeleted"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "date_last_modified"' do
    it 'should work' do
      expect(@instance.date_last_modified).to be_a(DateTime)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      expect(@instance.metadata).to be_a(Hash)
    end
  end

end
