=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::LineItemsType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LineItemsType' do
  before do
    # run before each test
    obj = build(:one_roster_line_item)
    @instance = OneRosterClient::LineItemsType.build_from_hash({:lineItems => [obj.to_hash]})
  end

  after do
    # run after each test
  end

  describe 'test an instance of LineItemsType' do
    it 'should create an instance of LineItemsType' do
      expect(@instance).to be_instance_of(OneRosterClient::LineItemsType)
    end
  end
  describe 'test attribute "line_items"' do
    it 'should work' do
      expect(@instance.line_items).to be_a(Array)
    end
    it 'contains line_items' do
      @instance.line_items.each do |item|
        expect(item).to be_a(OneRosterClient::LineItemType)
      end
    end
  end

end
