=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::LineItemType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LineItemType' do
  before do
    # run before each test
    obj = build(:one_roster_line_item)
    @instance = OneRosterClient::LineItemType.build_from_hash(obj.to_hash)
  end

  after do
    # run after each test
  end

  describe 'test an instance of LineItemType' do
    it 'should create an instance of LineItemType' do
      expect(@instance).to be_instance_of(OneRosterClient::LineItemType)
    end
  end
  describe 'test attribute "title"' do
    it 'should work' do
      expect(@instance.title).to be_a(String)
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      expect(@instance.description).to be_a(String)
    end
  end

  describe 'test attribute "assign_date"' do
    it 'should work' do
      expect(@instance.assign_date).to be_a(DateTime)
    end
  end

  describe 'test attribute "due_date"' do
    it 'should work' do
      expect(@instance.due_date).to be_a(DateTime)
    end
  end

  describe 'test attribute "_class"' do
    it 'should work' do
      expect(@instance._class).to be_a(OneRosterClient::GUIDRefType)
    end
  end

  describe 'test attribute "category"' do
    it 'should work' do
      expect(@instance.category).to be_a(OneRosterClient::GUIDRefType)
    end
  end

  describe 'test attribute "grading_period"' do
    it 'should work' do
      expect(@instance.grading_period).to be_a(OneRosterClient::GUIDRefType)
    end
  end

  describe 'test attribute "result_value_min"' do
    it 'should work' do
      expect(@instance.result_value_min).to be_a(Float)
    end
  end

  describe 'test attribute "result_value_max"' do
    it 'should work' do
      expect(@instance.result_value_max).to be_a(Float)
    end
  end

  describe 'test attribute "sourced_id"' do
    it 'should work' do
      expect(@instance.sourced_id).to be_a(String)
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      expect(@instance.status).to be_a(String)
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["active", "tobedeleted"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "date_last_modified"' do
    it 'should work' do
      expect(@instance.date_last_modified).to be_a(DateTime)
    end
  end

  describe 'test attribute "metadata"' do
    it 'should work' do
      expect(@instance.metadata).to be_a(Object)
    end
  end

end
