=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::MultipleAcademicSessionsType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MultipleAcademicSessionsType' do
  before do
    # run before each test
    obj = build(:one_roster_academic_session)
    @instance = OneRosterClient::MultipleAcademicSessionsType.build_from_hash({:academicSessions => [obj.to_hash]})
  end

  after do
    # run after each test
  end

  describe 'test an instance of MultipleAcademicSessionsType' do
    it 'should create an instance of MultipleAcademicSessionsType' do
      expect(@instance).to be_instance_of(OneRosterClient::MultipleAcademicSessionsType)
    end
  end
  describe 'test attribute "academic_sessions"' do
    it 'should work' do
      expect(@instance.academic_sessions).to be_a(Array)
    end
    it 'contains academic_sessions' do
      @instance.academic_sessions.each do |item|
        expect(item).to be_a(OneRosterClient::AcademicSessionType)
      end
    end
  end

end
