=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::ResourcesType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResourcesType' do
  before do
    # run before each test
    @instance = OneRosterClient::ResourcesType.build_from_hash({:resources => []})
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResourcesType' do
    it 'should create an instance of ResourcesType' do
      expect(@instance).to be_instance_of(OneRosterClient::ResourcesType)
    end
  end
  describe 'test attribute "resources"' do
    it 'should work' do
      expect(@instance.resources).to be_a(Array)
    end
  end

end
