=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::SingleEnrollmentType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SingleEnrollmentType' do
  before do
    # run before each test
    factory = build(:one_roster_single_enrollment)
    @instance = OneRosterClient::SingleEnrollmentType.build_from_hash factory.to_hash
  end

  after do
    # run after each test
  end

  describe 'test an instance of SingleEnrollmentType' do
    it 'should create an instance of SingleEnrollmentType' do
      expect(@instance).to be_instance_of(OneRosterClient::SingleEnrollmentType)
    end
  end
  describe 'test attribute "enrollment"' do
    it 'should be an EnrollmentType' do
      expect(@instance.enrollment).to be_instance_of(OneRosterClient::EnrollmentType)
    end
  end

end
