=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::UserIdType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UserIdType' do
  before do
    obj = build(:one_roster_user_id)
    @instance = OneRosterClient::UserIdType.build_from_hash(obj.to_hash)
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserIdType' do
    it 'should create an instance of UserIdType' do
      expect(@instance).to be_instance_of(OneRosterClient::UserIdType)
    end
  end
  describe 'test attribute "type"' do
    it 'should work' do
      expect(@instance.type).to be_a(String)
    end
  end

  describe 'test attribute "identifier"' do
    it 'should work' do
      expect(@instance.identifier).to be_a(String)
    end
  end

end
