=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OneRosterClient::UsersType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersType' do
  before do
    # run before each test
    obj = build(:one_roster_user)
    @instance = OneRosterClient::UsersType.build_from_hash({:users => [obj.to_hash]})
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersType' do
    it 'should create an instance of UsersType' do
      expect(@instance).to be_instance_of(OneRosterClient::UsersType)
    end
  end
  describe 'test attribute "users"' do
    it 'should work' do
      expect(@instance.users).to be_a(Array)
    end

    it 'contains users' do
      @instance.users.each do |user|
        expect(user).to be_a(OneRosterClient::UserType)
      end
    end
  end

end
