=begin
#OneRoster OpenAPI (JSON) Definition

#The OneRoster service binding is available in WSDL/XSD and REST/JSON. The model is based upon the IMS PSM modelling approach.

OpenAPI spec version: 1.1
Contact: platform@strongmind.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'oneroster_client/api_client'
require 'oneroster_client/api_error'
require 'oneroster_client/version'
require 'oneroster_client/configuration'

# Models
require 'oneroster_client/models/academic_session_type'
require 'oneroster_client/models/academic_session_type_all_of'
require 'oneroster_client/models/base_type'
require 'oneroster_client/models/categories_type'
require 'oneroster_client/models/category_type'
require 'oneroster_client/models/category_type_all_of'
require 'oneroster_client/models/class_type'
require 'oneroster_client/models/class_type_all_of'
require 'oneroster_client/models/classes_type'
require 'oneroster_client/models/course_type'
require 'oneroster_client/models/course_type_all_of'
require 'oneroster_client/models/courses_type'
require 'oneroster_client/models/demographic_type'
require 'oneroster_client/models/demographic_type_all_of'
require 'oneroster_client/models/demographics_type'
require 'oneroster_client/models/enrollment_type'
require 'oneroster_client/models/enrollment_type_all_of'
require 'oneroster_client/models/enrollments_type'
require 'oneroster_client/models/guid_ref_type'
require 'oneroster_client/models/guid_type'
require 'oneroster_client/models/identifier_type'
require 'oneroster_client/models/imsx_code_minor_field_type'
require 'oneroster_client/models/imsx_code_minor_type'
require 'oneroster_client/models/imsx_status_info_type'
require 'oneroster_client/models/line_item_type'
require 'oneroster_client/models/line_item_type_all_of'
require 'oneroster_client/models/line_items_type'
require 'oneroster_client/models/metadata_type'
require 'oneroster_client/models/multiple_academic_sessions_type'
require 'oneroster_client/models/org_type'
require 'oneroster_client/models/org_type_all_of'
require 'oneroster_client/models/orgs_type'
require 'oneroster_client/models/resource_type'
require 'oneroster_client/models/resource_type_all_of'
require 'oneroster_client/models/resources_type'
require 'oneroster_client/models/result_type'
require 'oneroster_client/models/result_type_all_of'
require 'oneroster_client/models/results_type'
require 'oneroster_client/models/single_academic_session_type'
require 'oneroster_client/models/single_category_type'
require 'oneroster_client/models/single_class_type'
require 'oneroster_client/models/single_course_type'
require 'oneroster_client/models/single_demographics_type'
require 'oneroster_client/models/single_enrollment_type'
require 'oneroster_client/models/single_line_item_type'
require 'oneroster_client/models/single_org_type'
require 'oneroster_client/models/single_resource_type'
require 'oneroster_client/models/single_result_type'
require 'oneroster_client/models/single_user_type'
require 'oneroster_client/models/user_id_type'
require 'oneroster_client/models/user_type'
require 'oneroster_client/models/user_type_all_of'
require 'oneroster_client/models/users_type'

# APIs
require 'oneroster_client/api/academic_sessions_management_api'
require 'oneroster_client/api/categories_management_api'
require 'oneroster_client/api/classes_management_api'
require 'oneroster_client/api/courses_management_api'
require 'oneroster_client/api/demographics_management_api'
require 'oneroster_client/api/enrollments_management_api'
require 'oneroster_client/api/grading_periods_management_api'
require 'oneroster_client/api/line_items_management_api'
require 'oneroster_client/api/orgs_management_api'
require 'oneroster_client/api/resources_management_api'
require 'oneroster_client/api/results_management_api'
require 'oneroster_client/api/schools_management_api'
require 'oneroster_client/api/students_management_api'
require 'oneroster_client/api/teachers_management_api'
require 'oneroster_client/api/terms_management_api'
require 'oneroster_client/api/users_management_api'

module OneRosterClient
  class << self
    # Customize default settings for the SDK using block.
    #   OneRosterClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
